### ISSUE TITLE
Problem to start using the lib

### ISSUE THREAD

**Issue by csarcom** [barseghyanartur/graphene-elastic#24]
Hello @barseghyanartur 

I'm having a little problem to get everything up and running, I'm new with elastic and graphql, maybe that's the reason :laughing: 

I have a consumer(RabbitMQ) app that populates elasticsearch on index "animal" with this kind of data[1]

I created another app(API) to consume this data from elastic, and I'm trying to use graphene-elastic for that, so far this is what I have[2]. For now, I just want to filter using the field "_id".

My problem so far:

>   File "/usr/local/lib/python3.6/site-packages/graphene_elastic/fields.py", line 89, in type
>     ), "The type {} doesn't have a connection".format(_type.__name__)
> AssertionError: The type Animal doesn't have a connection

That connection is the elasticsearch connection? Where should I declare my hostname and port for elastic?

[1] https://gist.github.com/csarcom/a9980a8bf62358e6a0b9e019469c9cd9
[2] https://gist.github.com/csarcom/0873f6e7816f7b75240a3828e11a7136

**Comment by barseghyanartur** [comment]
@csarcom:

You can't use ``_id`` as field name.

Check the examples I just wrote for you:

- https://github.com/barseghyanartur/graphene-elastic/blob/master/examples/schema/animal.py
- https://github.com/barseghyanartur/graphene-elastic/blob/master/examples/search_index/documents/animal.py

After populating some data, the following query works for me:

```
query {
 	animals(filter:{action:{term:"authority"}}) {
    pageInfo {
      hasNextPage
      hasNextPage
      startCursor
      endCursor
    }
    edges{
      node {
        scope
        action
        entity
        id 
        app
        messageId
        publishDate
        data
        uuid
      }
    }
  }
}
```

Since that was your case, I also made a read only document (``ReadOnlyAnimal``). That one works as well.
