### ISSUE TITLE
How to use connection between indices

### ISSUE THREAD

**Issue by datavistics** [barseghyanartur/graphene-elastic#42]
I looked in the documentation and couldnt find anything. 
Say I have some indices defined like this
```python
class Student(Document):
    name = Text()
    teacher = Text()

class Teachers(Document):
    name = Text()
```
If the teacher field is the Teacher id: How can I create a connection between the student and the teacher?

**Comment by barseghyanartur** [comment]
@datavistics:

On the Elastic part, if you want to search, you should carefully think of how do you want to structure your data. Basically, if you in that case you should index your data as:

```
class Student(Document):
    name = Text()
    teacher = Nested(...)  # Replace with
```

See [official docs](https://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#document).

However, nested queries are not yet implemented in this library in a generic way. For your that should involve some custom code, instead of generic declarative approach (which is strictly followed in all implemented features). Basically, you should implement a custom search tailored for your needs and use it upon need.

**Comment by datavistics** [comment]
Is there a way to use a connection field like in the graphene docs?
https://docs.graphene-python.org/en/latest/relay/connection/

**Comment by barseghyanartur** [comment]
I haven't [finalised that part](https://github.com/barseghyanartur/graphene-elastic/blob/master/src/graphene_elastic/relay/connection.py#L173), because it's not how it shall be done in Elasticsearch.
